Department facilities
salman-bhai/NITKWebsite pull request #36
Opened 2017-05-02 20:04 UTC by utkarsh23

Resolved #32 

Laptop Screen:
![1](https://cloud.githubusercontent.com/assets/12075549/25636806/2c2f5618-2fa0-11e7-84ac-a80a12b6f040.png)
![2](https://cloud.githubusercontent.com/assets/12075549/25636818/322ef302-2fa0-11e7-9d1a-ff6723959573.png)
![3](https://cloud.githubusercontent.com/assets/12075549/25636820/35122986-2fa0-11e7-8612-5ab0c17f9745.png)

Tablet Screen:
![4](https://cloud.githubusercontent.com/assets/12075549/25636839/41d3bdb0-2fa0-11e7-9770-57bf47369ed5.png)
![5](https://cloud.githubusercontent.com/assets/12075549/25636837/41bce90a-2fa0-11e7-9b44-cede8f7aaa4f.png)
![6](https://cloud.githubusercontent.com/assets/12075549/25636838/41d36d1a-2fa0-11e7-836b-b4f02cd8c581.png)

Mobile Screen:
![7](https://cloud.githubusercontent.com/assets/12075549/25636869/5b1b48ec-2fa0-11e7-9d5c-0db8115dd03e.png)
![8](https://cloud.githubusercontent.com/assets/12075549/25636919/96a07162-2fa0-11e7-9f49-46578d27cc0a.png)
![9](https://cloud.githubusercontent.com/assets/12075549/25636920/96a15096-2fa0-11e7-929c-05f82d6ad754.png)

2017-05-05 11:25 UTC, sbshah97 requested changes
Reduce amount of text in Mobile View

2017-05-05 17:06 UTC, sbshah97 submitted a review, later dismissed

2017-05-05 17:07 UTC, utkarsh23 commented
@salman-bhai @Hrily 
Changes made:
> Facilities menu [General Facilities, Lab Facilities, ...] is accessible on scroll
> Hide image description on screen

![10](https://cloud.githubusercontent.com/assets/12075549/25756396/4329e2d4-31e4-11e7-980c-db2c729b8aae.png)

![11](https://cloud.githubusercontent.com/assets/12075549/25756397/4372e178-31e4-11e7-9e14-dc448f4e4e50.png)

![12](https://cloud.githubusercontent.com/assets/12075549/25756398/43abc5d8-31e4-11e7-9cf7-a23fddbe2392.png)

![13](https://cloud.githubusercontent.com/assets/12075549/25756399/43aeab9a-31e4-11e7-9694-4aeb7122e448.png)

2017-05-06 06:53 UTC, sbshah97 approved these changes
Looks fine to me. Good work again!

2017-05-06 06:53 UTC, merged