Department Achievements
salman-bhai/NITKWebsite pull request #38
Opened 2017-05-04 21:20 UTC by mishal23

The previous pull-request wasn't complete with respect to the task-assigned, so that pull-request was closed by me without merging.

**Mobile ScreenShots:-**
![screenshot 65](https://cloud.githubusercontent.com/assets/21958074/25725347/338c1f88-313d-11e7-8893-6ed9e96da092.png)
![screenshot 66](https://cloud.githubusercontent.com/assets/21958074/25725360/3cb97196-313d-11e7-9515-e83b2e7b39bd.png)
![screenshot 67](https://cloud.githubusercontent.com/assets/21958074/25725366/424eef82-313d-11e7-86ef-57ba2dd76418.png)

**Desktop ScreenShots:-**
![screenshot 62](https://cloud.githubusercontent.com/assets/21958074/25725374/52a7bdc8-313d-11e7-930d-5b6f21ccf97f.png)
![screenshot 63](https://cloud.githubusercontent.com/assets/21958074/25725379/57b592ae-313d-11e7-94c7-848e2586a49d.png)
![screenshot 64](https://cloud.githubusercontent.com/assets/21958074/25725385/5df30624-313d-11e7-8a84-7e25221ca139.png)

2017-05-05 11:27 UTC, sbshah97 reviewed
Looks fine to me. We'll wait for @Hrily ka review and then merge your PR

2017-05-06 06:49 UTC, sbshah97 requested changes
Use white background for table elements in Student and Alumni tabs as well!

2017-05-06 12:24 UTC, mishal23 commented
Added White Background for Alumni & Students Page, and removed hover class for all the tables.
ScreenShot for the changes made.

![screenshot 73](https://cloud.githubusercontent.com/assets/21958074/25772274/003bc39c-3285-11e7-91de-5d5e0efc9de2.png)

2017-05-06 17:59 UTC, sbshah97 approved these changes

2017-05-06 18:00 UTC, merged