Design faculty_non_teaching.html
salman-bhai/NITKWebsite pull request #51
Opened 2017-05-07 13:38 UTC by utkarsh23

Resolved #49 

Desktop Screen:

![18](https://cloud.githubusercontent.com/assets/12075549/25781475/83ae1404-3358-11e7-8f65-ea2ebb53f229.png)

![19](https://cloud.githubusercontent.com/assets/12075549/25781474/83a722b6-3358-11e7-96a3-c047b4e20b4f.png)

![14](https://cloud.githubusercontent.com/assets/12075549/25781436/efecedbc-3357-11e7-89d6-6cdac37b2822.png)

Tablet Screen:

![16](https://cloud.githubusercontent.com/assets/12075549/25781437/f033bbe8-3357-11e7-91b0-5ad1919be14b.png)

Mobile Screen:

![17](https://cloud.githubusercontent.com/assets/12075549/25781438/f05ca846-3357-11e7-8e93-398970f44783.png)

2017-05-07 15:27 UTC, sbshah97 requested changes
Try putting the image next to each other instead of the image and the text below it! No one might scroll this much. Plus there's too much whitespace which can be utilized effectively! Do it both for desktop and mobile and see how it comes out!

2017-05-08 09:43 UTC, Hrily requested changes
Try using list instead of image and text below it.
Use image icons as bullets for list

2017-05-08 10:33 UTC, utkarsh23 commented
@salman-bhai @Hrily 
This is how it looks after changing the design

Desktop screen:

![20](https://cloud.githubusercontent.com/assets/12075549/25800614/b342b72e-3407-11e7-8efe-93457e9be017.png)

![21](https://cloud.githubusercontent.com/assets/12075549/25800615/b343405e-3407-11e7-9b89-25eafe39c73e.png)

![22](https://cloud.githubusercontent.com/assets/12075549/25800616/b343f422-3407-11e7-873f-cb19e9b5c240.png)

Tablet screen:

![23](https://cloud.githubusercontent.com/assets/12075549/25800617/b3464a06-3407-11e7-873d-dd5e99098f70.png)

Mobile screen:

![24](https://cloud.githubusercontent.com/assets/12075549/25800618/b34ec9e2-3407-11e7-8254-9bcfa3c9cbb9.png)

2017-05-08 16:51 UTC, Hrily approved these changes

2017-05-09 12:41 UTC, sbshah97 approved these changes

2017-05-09 12:41 UTC, merged